
name: "Docs Check"
on: pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'
    steps:
      # got from here: https://github.com/marketplace/actions/python-dependency-installation
      # should install dependencies in requirements.txt
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
    - name: Move to docs folder and build
      run: |
        cd doc
        pwd
        sphinx-build -T -E -W -b html . _build
